### ISSUE TITLE
Incompatibilities with dgeni-packages 0.13.x

### ISSUE THREAD

**Issue by wrporter** [wingedfox/dgeni-alive#14]
With version 0.13.x of `dgeni-packages`, there is a bug in `checkAnchorLinks.js` on line 13 where existence of `doc.outputPath` is not checked. I recommend upgrading to 0.16.0.

Also, there is a bug when using the `examples-ext` package, where `path` is not defined. The following line should be added at the top of the file.

``` js
var path = require('path');
```

**Comment by wingedfox** [comment]
Hi,

Thank you for the report, update will take a time because dgeni-packages upgraded nunjucks which requires to update all templates.

**Comment by wrporter** [comment]
@wingedfox if you give me access, I can submit a pull request. I've already done all the work.

**Comment by wingedfox** [comment]
Merged.
